In [8]:
import Video_List_Interface

In [9]:
fg = Video_List_Interface.VideoListInterface()

Reading from the Internal CSV File

In [14]:
fg.cal_Display()

,VIDEO Name,VIDEO Discription,Raw VIDEO Present,ContaingFrameNumber VIDEO Present
0,1a,aaa,True,False
1,2b,bbb,True,False
2,3c,ccc,False,False
3,4d,ddd,True,False
4,5e,eee,True,False

In [ ]:
fg.cal_Insert_All_Raw_Video_Files('''Your Input Video Files''')

In [13]:
fg.cal_Display()

,VIDEO Name,VIDEO Discription,Raw VIDEO Present,ContaingFrameNumber VIDEO Present
0,1a,aaa,True,False
1,2b,bbb,True,False
2,3c,ccc,False,False
3,4d,ddd,True,False
4,5e,eee,True,False

In [ ]:
fg.cal_Read_Data_From_File_And_Trim('''Your File Location''')